package com.rimboard.keyboard.engine

import com.rimboard.keyboard.model.StripLayout
import org.junit.After
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import java.io.File
import java.util.Locale

/**
 * Typing in two languages without switching between them.
 *
 * The whole of this path was unmeasured: **no test anywhere passed `altLang`**,
 * though every bilingual user goes through it on every keystroke, and the code
 * behind it is substantial — a second dictionary merged into the candidate
 * list, a cross-language correction fallback, per-language casing.
 *
 * ## What it is worth, and what it cost
 *
 * The feature earns its place. Keystrokes saved over real prose:
 *
 *                        typing en    typing tr
 *     en only              37.8          1.4
 *     en + tr              36.2         29.9
 *     tr only               8.7         32.0
 *     tr + en              35.1         30.6
 *
 * Regenerated by `the value of the second language, all four configurations`
 * rather than transcribed. The first version of this table was taken by hand
 * from a harness that started each measurement on a cold engine, and the
 * keystroke path does not load a prediction model -- it reports it absent and
 * asks a background thread for it -- so every cell also contained however much
 * of the corpus went past before the model landed. That is a property of the
 * machine, not of the blend: the cross-language cell read 32.8 that way, 34.1
 * run alone on an idle laptop, and 35.1 with the model resident before the
 * first keystroke, which is the only one of the three that is about this code.
 *
 * But it used to be paid for by the primary language, unevenly: adding English
 * cost Turkish **3.2 points of its own typing** while adding Turkish cost
 * English 0.4. That asymmetry had nothing to do with the languages.
 *
 * ## The cause: two lists, two scales
 *
 * A raw count is meaningless across corpora. English was counted from 728
 * million tokens and Turkish from 215 million, so the same word at the same
 * rank carries a five-times larger number in the English list — at rank 100,
 * 1,166,914 against 222,447. The blend discounted the second language by 0.85
 * and merged the raw numbers, so "slightly below" was in fact comfortably
 * above, precisely among the common words completions are drawn from.
 *
 * Dividing by [Dictionary.tokenTotal] first is what makes the discount mean
 * what it says. The same trap `CORRECTION_TARGET_CAP` documents, in a different
 * place and found the same way — by asking what a number means rather than what
 * it is.
 */
class BilingualTest {

    private lateinit var dir: File
    private lateinit var userData: UserData

    @Before
    fun setUp() {
        dir = File.createTempFile("rimboard-bi", "").let { it.delete(); it.mkdirs(); it }
        userData = UserData.inDir(dir)
    }

    @After
    fun tearDown() {
        userData.shutdown()
        dir.deleteRecursively()
    }

    private fun assets(): File =
        listOf(File("src/main/assets"), File("app/src/main/assets")).first { it.isDirectory }

    private fun fixtures(): File =
        listOf(File("src/test/fixtures"), File("app/src/test/fixtures")).first { it.isDirectory }

    @Test
    fun `every savings harness makes its models resident first`() {
        // A ratchet, because the failure is silent and the fix is one line
        // somebody could reasonably delete as redundant. Without it a harness
        // measures the warm thread's luck, the number drifts by a point or two
        // between runs, and the test that notices is whichever one sits
        // closest to its own threshold -- which is how this was found: a
        // cross-language assertion that passed alone and failed in the suite.
        val dir = listOf(File("src/test/java"), File("app/src/test/java"))
            .first { it.isDirectory }
            .resolve("com/rimboard/keyboard/engine")
        for (name in listOf("BilingualTest.kt", "StripAccuracyTest.kt")) {
            val src = dir.resolve(name).readText()
            // Split so the scan cannot match itself, which is exactly what it
            // did on the first run -- reporting BilingualTest as unfixed while
            // reading its own source above the code it was looking for.
            val loop = src.indexOf("var key" + "strokes = 0")
            assertTrue("$name no longer counts keystrokes", loop > 0)
            val before = src.substring(0, loop)
            assertTrue(
                "$name builds an engine and starts typing without loading the " +
                    "prediction model, so it measures the background warm-up too",
                before.contains("e.predictions(" + '"' + '"' + ", " + '"' + "x" + '"') ||
                    before.contains("engine.predictions(" + '"' + '"' + ", " + '"' + "x" + '"')
            )
        }
    }

    private fun engine(vararg langs: String): SuggestionEngine {
        val files = HashMap<String, String>()
        for (l in langs) {
            files["dictionaries/$l.txt"] = File(assets(), "dictionaries/$l.txt").readText()
            files["predictions/$l.txt"] = File(assets(), "predictions/$l.txt").readText()
        }
        return SuggestionEngine.forTesting(userData) { p -> files[p]?.byteInputStream() }
    }

    private fun sentences(lang: String, locale: Locale, n: Int): List<List<String>> =
        File(fixtures(), "prose_$lang.txt").readLines().filter { it.isNotBlank() }.take(n)
            .map { line ->
                val sb = StringBuilder()
                val out = ArrayList<String>()
                for (c in line) {
                    if (c.isLetter() || c == '\'' || c == '’') sb.append(c)
                    else { if (sb.isNotEmpty()) out.add(sb.toString()); sb.setLength(0) }
                }
                if (sb.isNotEmpty()) out.add(sb.toString())
                out.map { it.trim('\'').lowercase(locale) }.filter { it.length > 1 }
            }

    /**
     * The three chips actually shown; see StripAccuracyTest for why not items.
     *
     * [alt] is passed to [SuggestionEngine.acceptedWord] because the keyboard
     * passes it (`arrangeUnknownWord` in the service). Leaving it out here
     * quoted every word of the *other* language as unrecognised, so it never
     * matched the target and the harness reported words as "never offered"
     * that the strip was showing all along -- 7.8% of Turkish, all of it the
     * instrument.
     */
    private fun strip(
        e: SuggestionEngine, res: SuggestionsResult, lang: String, locale: Locale,
        alt: String?, altLocale: Locale?
    ): List<String> {
        val verbatim = res.items.firstOrNull() ?: return emptyList()
        val known = e.acceptedWord(verbatim, lang, locale, alt, altLocale)
        return StripLayout.arrange(res.items, res.autocorrectIndex, known) { "“$it”" }.words
    }

    /** Keystrokes saved typing [corpus] with [lang] primary and [alt] second. */
    private fun saved(lang: String, alt: String?, corpus: String): Double {
        val locale = Locale.forLanguageTag(lang)
        val altLocale = alt?.let { Locale.forLanguageTag(it) }
        val langs = if (alt == null) listOf(lang, corpus) else listOf(lang, alt, corpus)
        val e = engine(*langs.toTypedArray())
        // The test above says why, for the engine it builds by hand: mayLoad is
        // false on the keystroke path, so a model still being warmed in the
        // background is absent, and the number then depends on how quickly the
        // machine got round to loading it. This harness did not do it, which is
        // why it read 34.1% alone and 32.7% inside the full suite.
        for (l in langs.distinct()) {
            val lc = Locale.forLanguageTag(l)
            e.dictionary(l, lc)
            e.predictions("", "x", l, lc, 1)
        }
        var keystrokes = 0
        var baseline = 0
        for (sentence in sentences(corpus, Locale.forLanguageTag(corpus), 60)) {
            for ((i, w) in sentence.withIndex()) {
                baseline += w.length + 1
                val prev = if (i >= 1) sentence[i - 1] else ""
                val prev2 = if (i >= 2) sentence[i - 2] else ""
                var taken = -1
                for (k in 1..w.length) {
                    val res = e.suggestionsFor(
                        w.substring(0, k), lang, locale,
                        allowAutocorrect = true, personalized = false,
                        altLang = alt, altLocale = altLocale,
                        prevWord2 = prev2, prevWord = prev
                    )
                    if (strip(e, res, lang, locale, alt, altLocale)
                            .any { it.equals(w, ignoreCase = true) }) {
                        taken = k; break
                    }
                }
                keystrokes += if (taken < 0) w.length + 1 else taken + 1
            }
        }
        return (1.0 - keystrokes.toDouble() / baseline) * 100
    }

    @Test
    fun `the two shipped dictionaries really are on different scales`() {
        // The fact the blend has to divide out, asserted so that a rebuild of
        // the assets which happened to equalise them would not quietly make
        // the normalisation untested rather than unnecessary.
        val en = engine("en").dictionary("en", Locale.ENGLISH)
        val tr = engine("tr").dictionary("tr", Locale.forLanguageTag("tr"))
        assertTrue("both dictionaries must report a corpus size",
            en.tokenTotal > 0 && tr.tokenTotal > 0)
        val ratio = en.tokenTotal.toDouble() / tr.tokenTotal
        assertTrue(
            "English and Turkish were built from similar amounts of text " +
                "(ratio $ratio), so nothing here is measuring what it claims",
            ratio > 2.0
        )
    }

    @Test
    fun `a second language costs the first very little`() {
        // The regression this exists for. Turkish used to lose 3.2 points of
        // its own typing for having English switched on.
        val alone = saved("tr", null, "tr")
        val withEnglish = saved("tr", "en", "tr")
        val cost = alone - withEnglish
        println("tr alone %.1f%%, tr+en %.1f%%, cost %.1f points".format(alone, withEnglish, cost))
        assertTrue(
            "enabling English cost Turkish %.1f points of its own typing (%.1f -> %.1f); "
                .format(cost, alone, withEnglish) +
                "it was 3.2 before the corpus scales were divided out",
            cost < 2.0
        )
    }

    @Test
    fun `the second language still does its job`() {
        // The other half of the trade, so the test above cannot be satisfied
        // by simply ignoring the second language.
        val without = saved("tr", null, "en")
        val with = saved("tr", "en", "en")
        println("typing en on tr: alone %.1f%%, with en enabled %.1f%%".format(without, with))
        assertTrue(
            "a second language must transform typing it (%.1f -> %.1f)".format(without, with),
            with > without + 15.0
        )
    }

    @Test
    fun `the other language gets context ranking too`() {
        // Context is worth six to nine points of keystroke savings, and
        // somebody typing their second language was getting none of it: the
        // word before is in that language, the primary's n-grams have never
        // seen it, so the rank map came back empty and every completion fell
        // back to raw frequency.
        //
        // Two things had to change together, which is why loading the second
        // model alone moved nothing: the map has to be built from both
        // languages, *and* the second language's candidates have to be
        // multiplied by it. Every other candidate source already was.
        val e = engine("tr", "en")
        val tr = Locale.forLanguageTag("tr")
        val en = Locale.ENGLISH
        // mayLoad is false on the keystroke path, so the models must be resident.
        e.dictionary("tr", tr); e.predictions("", "x", "tr", tr, 1)
        e.dictionary("en", en); e.predictions("", "x", "en", en, 1)

        val saved = saved("tr", "en", "en")
        println("typing English with Turkish primary: %.1f%% saved".format(saved))
        assertTrue(
            "typing the other language saved only %.1f%%; it was 32.8 before the ".format(saved) +
                "second language's n-grams were consulted and 35.1 after",
            saved > 34.0
        )
    }

    @Test
    fun `word-building rules follow the language, not the slot`() {
        // Turkish stacks suffixes whether it is the first language or the
        // second. "kitaplarımızda" is in no word list — it is a stem with four
        // endings on it — and the morphology rule is what makes it a word.
        // That rule was only ever asked about the *primary* language, so the
        // same Turkish typed by the same user was a word with Turkish selected
        // and a misspelling with English selected.
        val tr = Locale.forLanguageTag("tr")
        val en = Locale.ENGLISH
        val built = "kitaplarımızda"

        val trFirst = engine("tr")
        assertTrue(
            "the fixture must not be in the list verbatim, or this proves nothing",
            !trFirst.dictionary("tr", tr).contains(built)
        )
        assertTrue(
            "$built is a word when Turkish is the primary language",
            trFirst.acceptedWord(built, "tr", tr)
        )

        val enFirst = engine("en", "tr")
        assertTrue(
            "$built must be a word when Turkish is the *second* language too",
            enFirst.acceptedWord(built, "en", en, "tr", tr)
        )
        assertTrue(
            "and not merely because English accepts everything",
            !enFirst.acceptedWord(built, "en", en)
        )
    }

    @Test
    fun `the other language's words are accepted rather than underlined`() {
        // The fixture is derived rather than guessed, because guessing it got
        // this wrong: "because", "tomorrow" and "different" are all in the
        // *Turkish* list at 284, 187 and 64. Subtitle corpora are full of the
        // other language, so a hand-picked English word is quite likely to be
        // a Turkish entry too, and the negative half of this test would have
        // been asserting something false about three words in four.
        val e = engine("tr", "en")
        val tr = Locale.forLanguageTag("tr")
        val en = Locale.ENGLISH
        val onlyEnglish = File(assets(), "dictionaries/en.txt").useLines { lines ->
            lines.drop(200)
                .mapNotNull { it.split(' ').firstOrNull() }
                .filter { it.length in 5..10 && it.all { c -> c.isLetter() } }
                .filterNot { e.acceptedWord(it, "tr", tr) }
                .take(40)
                .toList()
        }
        assertTrue(
            "no English word was found that Turkish alone rejects, so this " +
                "measures nothing",
            onlyEnglish.size >= 20
        )
        val rescued = onlyEnglish.count { e.acceptedWord(it, "tr", tr, "en", en) }
        println("English words Turkish alone rejects: ${onlyEnglish.size}, " +
            "accepted once English is on: $rescued")
        assertTrue(
            "enabling English rescued only $rescued of ${onlyEnglish.size} " +
                "English words from being underlined: " + onlyEnglish.take(8),
            rescued == onlyEnglish.size
        )
    }

    /**
     * A third language, and which two of the three actually get blended.
     *
     * The engine holds one other language at a time, so with three enabled
     * *which* one is a real decision — and it used to be made by the order
     * [com.rimboard.keyboard.model.Languages].all is written in. Enabling en,
     * tr and de gave the pairs en+tr, tr+en and de+en, so German and Turkish
     * never met however much the user wrote both.
     *
     * This measures what that was worth, on the same corpus and the same
     * keystroke counter as everything else in this file. The rule that picks
     * the pair now lives in
     * [com.rimboard.keyboard.settings.SecondLanguageChoiceTest]; this is the
     * half that says the choice is worth making at all.
     */
    /**
     * The table at the top of this file, regenerated rather than remembered.
     *
     * It was written from numbers taken by hand, on a harness that measured the
     * engine's warm-up along with the engine -- so the cells were low by a
     * point or two each, unevenly, and re-running it never quite reproduced
     * them. Printed here so the claim the file opens with is one command away
     * from being checked, and so the next person to change the blend can see
     * which cell moved instead of which number they no longer trust.
     */
    @Test
    fun `the value of the second language, all four configurations`() {
        val rows = listOf(
            "en only" to Pair(saved("en", null, "en"), saved("en", null, "tr")),
            "en + tr" to Pair(saved("en", "tr", "en"), saved("en", "tr", "tr")),
            "tr only" to Pair(saved("tr", null, "en"), saved("tr", null, "tr")),
            "tr + en" to Pair(saved("tr", "en", "en"), saved("tr", "en", "tr"))
        )
        val out = StringBuilder("                   typing en    typing tr\n")
        for ((label, v) in rows)
            out.append("    %-10s %10.1f %12.1f%n".format(label, v.first, v.second))
        println(out)

        // The claim the table is quoted for: each language is better served by
        // its own keyboard, and adding the other costs a little rather than
        // ruining it. Asserted loosely -- the numbers are documentation, and a
        // threshold tight enough to pin them would break on every asset
        // rebuild -- but not so loosely that a blend which stopped working
        // would still pass.
        val (enAlone, _) = rows[0].second
        val (enBoth, trBoth) = rows[2].second.first to rows[3].second.second
        assertTrue(
            "English typed with English selected should still be the best English " +
                "in the table.\n$out",
            enAlone > rows[3].second.first
        )
        assertTrue(
            "enabling the second language should not cost the first more than " +
                "a couple of points.\n$out",
            rows[3].second.second > rows[2].second.second - 3.0 && trBoth > 25.0 && enBoth < 15.0
        )
    }

    @Test
    fun `pairing the right two of three languages is worth about thirty points`() {
        // German prose, typed on the Turkish layout, by a user who has English
        // enabled as well. English is what the old rule handed them.
        val wrongPair = saved("tr", "en", "de")
        val rightPair = saved("tr", "de", "de")
        val noSecond = saved("tr", null, "de")
        val lines = ("typing de on the tr layout: none %.1f%%, alt=en %.1f%%, alt=de %.1f%%")
            .format(noSecond, wrongPair, rightPair)
        println(lines)

        // The wrong second language is worth almost nothing, which is the
        // point: it is not a smaller benefit, it is the absence of one.
        assertTrue(
            "pairing Turkish with English did more for German prose than " +
                "expected, so this no longer measures a wasted slot.\n$lines",
            wrongPair - noSecond < 5.0
        )
        assertTrue(
            "pairing the two languages actually being typed must transform it.\n$lines",
            rightPair > wrongPair + 20.0
        )
    }
}
