#!/usr/bin/env python3
"""Generate the offline emoji search index.

Writes app/src/main/assets/emoji/search_<lang>.txt, one line per keyword:

    keyword<TAB>emoji1 emoji2 emoji3 ...

The emoji panel's search box matches the typed query as a prefix of these
keywords and shows the union of the matching emoji. Everything is on-device;
no network and no emoji-name dataset is bundled.

Provenance: the keyword -> emoji associations are common, non-creative labels
written by hand for RimBoard (not extracted from any external corpus or emoji
annotation dataset), so they carry no licensing constraints beyond MIT.

Run:  python3 tools/build_emoji_search.py
"""
import os

OUT_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "app", "src", "main", "assets", "emoji",
)

# keyword -> space separated emoji, most relevant first.
EN = {
    # faces / emotions
    "happy": "😊 😄 😁 🙂 😃 😀 😆 🥰 😍",
    "smile": "😊 😄 🙂 😁 😃",
    "laugh": "😂 🤣 😆 😹",
    "lol": "😂 🤣",
    "funny": "😂 🤣 😜",
    "sad": "😢 😞 😔 🙁 ☹️ 😟",
    "cry": "😭 😢 😿",
    "angry": "😠 😡 🤬 👿",
    "mad": "😡 😠 🤬",
    "love": "😍 🥰 😘 ❤️ 💕 💖",
    "kiss": "😘 😗 😚 💋 😙",
    "wink": "😉 😜",
    "cool": "😎 🆒",
    "wow": "😮 😯 😲 🤩",
    "shocked": "😱 😨 😳",
    "omg": "😱 😲 🤯",
    "think": "🤔 🧐",
    "confused": "😕 😟 🫤 😵",
    "worried": "😟 😧 😰",
    "scared": "😨 😱 😰",
    "sick": "🤒 🤢 🤮 🤧 😷",
    "tired": "😴 🥱 😪",
    "sleep": "😴 😪 💤",
    "bored": "😑 😐 🥱",
    "nervous": "😅 😬 😰",
    "shy": "😳 🥺 ☺️",
    "cute": "🥰 😍 🥺",
    "silly": "😜 🤪 😝",
    "crazy": "🤪 🤯",
    "rich": "🤑 💰",
    "hungry": "🤤 😋",
    "yum": "😋 🤤",
    "sunglasses": "😎 🕶️",
    "nerd": "🤓 🧐",
    "party": "🥳 🎉 🎊",
    "celebrate": "🥳 🎉 🎊 🍾",
    "hot": "🥵 🔥",
    "cold": "🥶 ❄️",
    "dizzy": "😵 💫",
    "mind": "🤯 🧠",
    "quiet": "🤫 🤐 😶",
    "lie": "🤥",
    "money": "🤑 💰 💵 💸",
    "sunglass": "😎",
    "grin": "😁 😀",
    "smirk": "😏",
    "neutral": "😐 😑",
    # gestures / hands / people
    "ok": "👌 🆗 ✅",
    "good": "👍 👌 🙆",
    "thumbsup": "👍",
    "thumbsdown": "👎",
    "bad": "👎",
    "clap": "👏",
    "wave": "👋",
    "hi": "👋",
    "hello": "👋",
    "bye": "👋",
    "pray": "🙏",
    "thanks": "🙏",
    "please": "🙏",
    "highfive": "🙌 ✋",
    "hand": "✋ 🖐️ 👋 🤚",
    "fist": "✊ 👊 🤛 🤜",
    "punch": "👊 🤛 🤜",
    "peace": "✌️",
    "victory": "✌️",
    "point": "👉 👈 👆 👇 ☝️",
    "muscle": "💪",
    "strong": "💪",
    "gym": "💪 🏋️",
    "hug": "🤗 🫂",
    "shrug": "🤷",
    "facepalm": "🤦",
    "cross": "🤞 🙏",
    "eyes": "👀 👁️",
    "look": "👀",
    "brain": "🧠",
    "baby": "👶",
    "boy": "👦 🧒",
    "girl": "👧 🧒",
    "man": "👨 🧑",
    "woman": "👩 🧑",
    "family": "👪 👨‍👩‍👧 👨‍👩‍👧‍👦",
    "police": "👮",
    "king": "🤴 👑",
    "queen": "👸 👑",
    "angel": "😇 👼",
    "devil": "😈 👿",
    "superhero": "🦸 🦹",
    "wizard": "🧙",
    "zombie": "🧟",
    "ghost": "👻",
    "vampire": "🧛",
    "clown": "🤡",
    "robot": "🤖",
    "alien": "👽 👾",
    "skull": "💀 ☠️",
    "dead": "💀 ☠️",
    "poop": "💩",
    "run": "🏃",
    "walk": "🚶",
    "dance": "💃 🕺",
    "swim": "🏊",
    "surf": "🏄",
    "bike": "🚴 🚲",
    "climb": "🧗",
    "yoga": "🧘",
    # hearts / symbols
    "heart": "❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎",
    "hearts": "❤️ 💕 💞 💓 💗 💖 💘 💝",
    "brokenheart": "💔",
    "sparkle": "✨ 🌟 💫",
    "star": "⭐ 🌟 ✨",
    "fire": "🔥",
    "lit": "🔥",
    "boom": "💥",
    "explosion": "💥",
    "hundred": "💯",
    "perfect": "💯",
    "check": "✅ ☑️ ✔️",
    "yes": "✅ 👍",
    "no": "❌ 🚫 👎",
    "cross_mark": "❌",
    "warning": "⚠️ 🚨",
    "stop": "🛑 ✋",
    "question": "❓ ❔",
    "exclamation": "❗ ❕",
    "recycle": "♻️",
    "infinity": "♾️",
    "music": "🎵 🎶",
    "note": "🎵 🎶",
    "bell": "🔔 🔕",
    "flag": "🚩 🏁 🏳️ 🏴",
    "rainbow": "🌈",
    "zzz": "💤",
    # animals
    "dog": "🐶 🐕 🦮",
    "puppy": "🐶 🐕",
    "cat": "🐱 🐈 😺 😸 😻",
    "kitten": "🐱 🐈",
    "mouse": "🐭 🐁",
    "rabbit": "🐰 🐇",
    "bunny": "🐰 🐇",
    "fox": "🦊",
    "bear": "🐻 🧸",
    "panda": "🐼",
    "koala": "🐨",
    "tiger": "🐯 🐅",
    "lion": "🦁",
    "cow": "🐮 🐄",
    "pig": "🐷 🐖",
    "frog": "🐸",
    "monkey": "🐵 🐒 🙈 🙉 🙊",
    "chicken": "🐔 🐓 🐣 🐤",
    "penguin": "🐧",
    "bird": "🐦 🕊️ 🦅",
    "duck": "🦆",
    "owl": "🦉",
    "eagle": "🦅",
    "bat": "🦇",
    "wolf": "🐺",
    "horse": "🐴 🐎 🦄",
    "unicorn": "🦄",
    "bee": "🐝",
    "bug": "🐛 🐜 🐞",
    "butterfly": "🦋",
    "snail": "🐌",
    "ladybug": "🐞",
    "ant": "🐜",
    "spider": "🕷️ 🕸️",
    "turtle": "🐢",
    "snake": "🐍",
    "dinosaur": "🦖 🦕",
    "octopus": "🐙",
    "squid": "🦑",
    "shrimp": "🦐",
    "crab": "🦀",
    "fish": "🐟 🐠 🐡 🎣",
    "dolphin": "🐬",
    "whale": "🐳 🐋",
    "shark": "🦈",
    "elephant": "🐘",
    "giraffe": "🦒",
    "zebra": "🦓",
    "monkey_face": "🐵",
    "snake_face": "🐍",
    "paw": "🐾",
    "dragon": "🐉 🐲",
    # nature / weather
    "flower": "🌸 🌷 🌹 🌻 🌼 💐",
    "rose": "🌹",
    "tree": "🌳 🌲 🌴",
    "plant": "🌱 🪴 🌿",
    "leaf": "🍀 🍃 🌿",
    "clover": "🍀",
    "sun": "☀️ 🌞",
    "sunny": "☀️",
    "moon": "🌙 🌛 🌝 🌚",
    "night": "🌙 🌃",
    "cloud": "☁️ ⛅",
    "rain": "🌧️ ☔",
    "storm": "⛈️ 🌩️",
    "snow": "❄️ ⛄ 🌨️",
    "snowman": "⛄ ☃️",
    "wind": "💨 🌬️",
    "water": "💧 💦 🌊",
    "wave": "🌊 👋",
    "ocean": "🌊",
    "earth": "🌍 🌎 🌏",
    "world": "🌍 🌎 🌏",
    "globe": "🌍 🌐",
    "mountain": "⛰️ 🏔️ 🗻",
    "volcano": "🌋",
    "beach": "🏖️ 🏝️",
    "desert": "🏜️",
    "lightning": "⚡",
    "comet": "☄️",
    "planet": "🪐",
    "space": "🚀 🌌 🪐",
    # food / drink
    "food": "🍕 🍔 🍟 🌮",
    "pizza": "🍕",
    "burger": "🍔",
    "fries": "🍟",
    "hotdog": "🌭",
    "taco": "🌮",
    "sandwich": "🥪",
    "sushi": "🍣 🍱",
    "rice": "🍚 🍙",
    "noodles": "🍜 🍝",
    "pasta": "🍝",
    "egg": "🥚 🍳",
    "bacon": "🥓",
    "meat": "🍖 🥩",
    "chicken_leg": "🍗",
    "bread": "🍞 🥖 🥐",
    "cheese": "🧀",
    "salad": "🥗",
    "fruit": "🍎 🍊 🍌 🍇 🍓",
    "apple": "🍎 🍏",
    "banana": "🍌",
    "orange": "🍊",
    "lemon": "🍋",
    "grape": "🍇",
    "strawberry": "🍓",
    "cherry": "🍒",
    "peach": "🍑",
    "watermelon": "🍉",
    "pineapple": "🍍",
    "coconut": "🥥",
    "avocado": "🥑",
    "tomato": "🍅",
    "corn": "🌽",
    "carrot": "🥕",
    "pepper": "🌶️ 🫑",
    "mushroom": "🍄",
    "potato": "🥔 🍟",
    "cake": "🎂 🍰 🧁",
    "birthday": "🎂 🥳 🎉",
    "cookie": "🍪",
    "chocolate": "🍫",
    "candy": "🍬 🍭",
    "donut": "🍩",
    "icecream": "🍦 🍨 🍧",
    "popcorn": "🍿",
    "honey": "🍯",
    "coffee": "☕",
    "tea": "🍵 🫖",
    "milk": "🥛",
    "juice": "🧃",
    "soda": "🥤",
    "beer": "🍺 🍻",
    "wine": "🍷",
    "cocktail": "🍸 🍹",
    "champagne": "🍾 🥂",
    "cheers": "🍻 🥂",
    "drink": "🥤 🍹 🍸",
    # activities / objects
    "gift": "🎁",
    "present": "🎁",
    "balloon": "🎈",
    "confetti": "🎊 🎉",
    "trophy": "🏆",
    "win": "🏆 🥇",
    "medal": "🏅 🥇 🥈 🥉",
    "gold": "🥇",
    "game": "🎮 🕹️",
    "dice": "🎲",
    "dart": "🎯",
    "target": "🎯",
    "art": "🎨",
    "camera": "📷 📸",
    "photo": "📸 🖼️",
    "movie": "🎬 🎥",
    "tv": "📺",
    "phone": "📱 ☎️ 📞",
    "call": "📞 ☎️",
    "computer": "💻 🖥️",
    "laptop": "💻",
    "keyboard": "⌨️",
    "mail": "📧 ✉️ 📨",
    "email": "📧 ✉️",
    "letter": "✉️ 📝",
    "book": "📖 📚",
    "study": "📚 📖 ✏️",
    "pencil": "✏️ 📝",
    "pen": "🖊️ 🖋️",
    "write": "✍️ 📝",
    "idea": "💡",
    "bulb": "💡",
    "light": "💡 🔦",
    "battery": "🔋",
    "plug": "🔌",
    "magnet": "🧲",
    "tool": "🔧 🔨 🛠️",
    "hammer": "🔨",
    "wrench": "🔧",
    "gear": "⚙️",
    "key": "🔑 🗝️",
    "lock": "🔒 🔓",
    "bell_notify": "🔔",
    "bomb": "💣",
    "gun": "🔫",
    "knife": "🔪",
    "pill": "💊",
    "syringe": "💉",
    "microscope": "🔬",
    "telescope": "🔭",
    "magnify": "🔍 🔎",
    "search": "🔍 🔎",
    "clock": "⏰ 🕐 ⏱️",
    "time": "⏰ ⌛ ⏳",
    "wait": "⏳ ⌛",
    "calendar": "📅 📆",
    "chart": "📊 📈 📉",
    "graph": "📈 📉 📊",
    "up": "📈 ⬆️ 🔼",
    "down": "📉 ⬇️ 🔽",
    "money_bag": "💰",
    "cash": "💵 💴 💶 💷",
    "card": "💳",
    "diamond": "💎",
    "ring": "💍",
    "crown": "👑",
    "bag": "🛍️ 👜 🎒",
    "shopping": "🛒 🛍️",
    "cart": "🛒",
    "shield": "🛡️",
    "trash": "🗑️",
    "toilet": "🚽",
    "bath": "🛁 🛀",
    "soap": "🧼",
    "broom": "🧹",
    "candle": "🕯️",
    "door": "🚪",
    "bed": "🛏️",
    "chair": "🪑",
    "mirror": "🪞",
    "umbrella": "☔ ☂️",
    "glasses": "👓 🕶️",
    "shirt": "👕",
    "shoe": "👟 👞",
    "hat": "🎩 🧢 👒",
    "dress": "👗",
    "crown_king": "👑",
    "magic": "✨ 🪄",
    "wand": "🪄",
    # travel / places
    "car": "🚗 🚙",
    "taxi": "🚕",
    "bus": "🚌",
    "truck": "🚚 🚛",
    "police_car": "🚓",
    "ambulance": "🚑",
    "fire_truck": "🚒",
    "motorcycle": "🏍️",
    "scooter": "🛵 🛴",
    "train": "🚆 🚄 🚂",
    "subway": "🚇",
    "plane": "✈️ 🛫",
    "travel": "✈️ 🧳 🗺️",
    "rocket": "🚀",
    "launch": "🚀",
    "helicopter": "🚁",
    "boat": "⛵ 🚤 🛥️",
    "ship": "🚢 ⛴️",
    "anchor": "⚓",
    "fuel": "⛽",
    "traffic": "🚦 🚥",
    "map": "🗺️ 🧭",
    "home": "🏠 🏡",
    "house": "🏠 🏡",
    "building": "🏢 🏬 🏥",
    "school": "🏫",
    "hospital": "🏥",
    "church": "⛪",
    "castle": "🏰 🏯",
    "tent": "⛺ 🏕️",
    "city": "🏙️ 🌆",
    "bridge": "🌉",
    "statue": "🗽",
    "ferris": "🎡",
    "circus": "🎪",
    "sport": "⚽ 🏀 🏈 ⚾",
    "soccer": "⚽",
    "football": "🏈 ⚽",
    "basketball": "🏀",
    "baseball": "⚾",
    "tennis": "🎾",
    "volleyball": "🏐",
    "golf": "⛳ 🏌️",
    "bowling": "🎳",
    "boxing": "🥊",
    "ski": "🎿 ⛷️",
    "skate": "⛸️ 🛹",
    "fishing": "🎣",
    "chess": "♟️",
    "guitar": "🎸",
    "piano": "🎹",
    "drum": "🥁",
    "trumpet": "🎺",
    "violin": "🎻",
    "mic": "🎤",
    "microphone": "🎤",
    "headphone": "🎧",
    "work": "💼",
    "briefcase": "💼",
}

# Turkish keyword -> emoji. Same emoji pools, Turkish search terms.
TR = {
    "mutlu": "😊 😄 😁 🥰",
    "gülümse": "😊 🙂 😄",
    "gül": "😂 🤣 😆",
    "komik": "😂 🤣",
    "üzgün": "😢 😞 😔 🙁",
    "ağla": "😭 😢",
    "kızgın": "😠 😡 🤬",
    "sinirli": "😡 😠",
    "aşk": "😍 🥰 😘 ❤️ 💕",
    "sevgi": "❤️ 🥰 😍 💕",
    "öpücük": "😘 😗 💋",
    "kalp": "❤️ 🧡 💛 💚 💙 💜 🖤",
    "ateş": "🔥",
    "yıldız": "⭐ 🌟 ✨",
    "harika": "💯 🤩",
    "tamam": "👌 ✅ 🆗",
    "evet": "✅ 👍",
    "hayır": "❌ 🚫 👎",
    "alkış": "👏",
    "selam": "👋",
    "merhaba": "👋",
    "teşekkür": "🙏",
    "lütfen": "🙏",
    "dua": "🙏",
    "güçlü": "💪",
    "kas": "💪",
    "göz": "👀 👁️",
    "beyin": "🧠",
    "hayalet": "👻",
    "robot": "🤖",
    "uzaylı": "👽",
    "kurukafa": "💀",
    "kaka": "💩",
    "koş": "🏃",
    "dans": "💃 🕺",
    "köpek": "🐶 🐕",
    "kedi": "🐱 🐈 😺",
    "tavşan": "🐰 🐇",
    "ayı": "🐻",
    "aslan": "🦁",
    "kaplan": "🐯 🐅",
    "at": "🐴 🐎",
    "kuş": "🐦 🦅",
    "balık": "🐟 🐠",
    "arı": "🐝",
    "kelebek": "🦋",
    "yılan": "🐍",
    "fil": "🐘",
    "çiçek": "🌸 🌷 🌹 💐",
    "gül_çiçek": "🌹",
    "ağaç": "🌳 🌲",
    "güneş": "☀️ 🌞",
    "ay": "🌙 🌝",
    "yağmur": "🌧️ ☔",
    "kar": "❄️ ⛄",
    "su": "💧 💦 🌊",
    "deniz": "🌊",
    "dünya": "🌍 🌎 🌏",
    "dağ": "⛰️ 🏔️",
    "şimşek": "⚡",
    "yemek": "🍕 🍔 🍟",
    "pizza": "🍕",
    "hamburger": "🍔",
    "meyve": "🍎 🍌 🍇",
    "elma": "🍎 🍏",
    "muz": "🍌",
    "portakal": "🍊",
    "çilek": "🍓",
    "pasta": "🎂 🍰",
    "doğumgünü": "🎂 🥳 🎉",
    "çikolata": "🍫",
    "dondurma": "🍦 🍨",
    "kahve": "☕",
    "çay": "🍵",
    "süt": "🥛",
    "bira": "🍺 🍻",
    "şarap": "🍷",
    "hediye": "🎁",
    "balon": "🎈",
    "kupa": "🏆",
    "oyun": "🎮 🕹️",
    "kamera": "📷 📸",
    "telefon": "📱 📞",
    "bilgisayar": "💻",
    "kitap": "📖 📚",
    "kalem": "✏️ 🖊️",
    "fikir": "💡",
    "anahtar": "🔑",
    "kilit": "🔒",
    "saat": "⏰ 🕐",
    "para": "💰 💵",
    "elmas": "💎",
    "taç": "👑",
    "araba": "🚗 🚙",
    "otobüs": "🚌",
    "tren": "🚆 🚄",
    "uçak": "✈️",
    "roket": "🚀",
    "gemi": "🚢 ⛵",
    "ev": "🏠 🏡",
    "okul": "🏫",
    "futbol": "⚽",
    "basketbol": "🏀",
    "müzik": "🎵 🎶",
    "gitar": "🎸",
    "parti": "🥳 🎉 🎊",
    "kutlama": "🥳 🎉",
}

# Core search terms for the other major bundled languages. Smaller than the
# English set on purpose: these cover the concepts people actually search for,
# and English stays available as a fallback for anything missing.
DE = {
    "gluecklich": "😊 😄 😁 🥰", "glücklich": "😊 😄 😁 🥰", "lachen": "😂 🤣 😆",
    "traurig": "😢 😞 😔 🙁", "weinen": "😭 😢", "wuetend": "😠 😡 🤬",
    "wütend": "😠 😡 🤬", "liebe": "😍 🥰 😘 ❤️ 💕", "herz": "❤️ 🧡 💛 💚 💙 💜 🖤",
    "kuss": "😘 💋", "feuer": "🔥", "stern": "⭐ 🌟 ✨", "danke": "🙏",
    "bitte": "🙏", "hand": "✋ 👋 🤚", "daumen": "👍 👎", "klatschen": "👏",
    "hallo": "👋", "tschuess": "👋", "tschüss": "👋", "stark": "💪",
    "auge": "👀 👁️", "gehirn": "🧠", "geist": "👻", "roboter": "🤖",
    "hund": "🐶 🐕", "katze": "🐱 🐈 😺", "hase": "🐰 🐇", "baer": "🐻",
    "bär": "🐻", "loewe": "🦁", "löwe": "🦁", "pferd": "🐴 🐎", "vogel": "🐦 🦅",
    "fisch": "🐟 🐠", "biene": "🐝", "schmetterling": "🦋", "schlange": "🐍",
    "elefant": "🐘", "blume": "🌸 🌷 🌹 💐", "rose": "🌹", "baum": "🌳 🌲",
    "sonne": "☀️ 🌞", "mond": "🌙 🌝", "regen": "🌧️ ☔", "schnee": "❄️ ⛄",
    "wasser": "💧 💦 🌊", "meer": "🌊", "erde": "🌍 🌎 🌏", "berg": "⛰️ 🏔️",
    "blitz": "⚡", "essen": "🍕 🍔 🍟", "pizza": "🍕", "burger": "🍔",
    "obst": "🍎 🍌 🍇", "apfel": "🍎 🍏", "banane": "🍌", "erdbeere": "🍓",
    "kuchen": "🎂 🍰", "geburtstag": "🎂 🥳 🎉", "schokolade": "🍫",
    "eis": "🍦 🍨", "kaffee": "☕", "tee": "🍵", "milch": "🥛", "bier": "🍺 🍻",
    "wein": "🍷", "geschenk": "🎁", "ballon": "🎈", "pokal": "🏆",
    "spiel": "🎮 🕹️", "kamera": "📷 📸", "telefon": "📱 📞", "computer": "💻",
    "buch": "📖 📚", "stift": "✏️ 🖊️", "idee": "💡", "schluessel": "🔑",
    "schlüssel": "🔑", "schloss": "🔒", "uhr": "⏰ 🕐", "geld": "💰 💵",
    "diamant": "💎", "krone": "👑", "auto": "🚗 🚙", "bus": "🚌",
    "zug": "🚆 🚄", "flugzeug": "✈️", "rakete": "🚀", "schiff": "🚢 ⛵",
    "haus": "🏠 🏡", "schule": "🏫", "fussball": "⚽", "fußball": "⚽",
    "musik": "🎵 🎶", "gitarre": "🎸", "party": "🥳 🎉 🎊", "ja": "✅ 👍",
    "nein": "❌ 🚫 👎", "ok": "👌 ✅",
}
ES = {
    "feliz": "😊 😄 😁 🥰", "reir": "😂 🤣 😆", "reír": "😂 🤣 😆",
    "triste": "😢 😞 😔 🙁", "llorar": "😭 😢", "enojado": "😠 😡 🤬",
    "amor": "😍 🥰 😘 ❤️ 💕", "corazon": "❤️ 🧡 💛 💚 💙 💜 🖤",
    "corazón": "❤️ 🧡 💛 💚 💙 💜 🖤", "beso": "😘 💋", "fuego": "🔥",
    "estrella": "⭐ 🌟 ✨", "gracias": "🙏", "favor": "🙏", "mano": "✋ 👋 🤚",
    "pulgar": "👍 👎", "aplauso": "👏", "hola": "👋", "adios": "👋",
    "adiós": "👋", "fuerte": "💪", "ojo": "👀 👁️", "cerebro": "🧠",
    "fantasma": "👻", "robot": "🤖", "perro": "🐶 🐕", "gato": "🐱 🐈 😺",
    "conejo": "🐰 🐇", "oso": "🐻", "leon": "🦁", "león": "🦁",
    "caballo": "🐴 🐎", "pajaro": "🐦 🦅", "pájaro": "🐦 🦅", "pez": "🐟 🐠",
    "abeja": "🐝", "mariposa": "🦋", "serpiente": "🐍", "elefante": "🐘",
    "flor": "🌸 🌷 🌹 💐", "rosa": "🌹", "arbol": "🌳 🌲", "árbol": "🌳 🌲",
    "sol": "☀️ 🌞", "luna": "🌙 🌝", "lluvia": "🌧️ ☔", "nieve": "❄️ ⛄",
    "agua": "💧 💦 🌊", "mar": "🌊", "tierra": "🌍 🌎 🌏", "montana": "⛰️ 🏔️",
    "montaña": "⛰️ 🏔️", "rayo": "⚡", "comida": "🍕 🍔 🍟", "pizza": "🍕",
    "hamburguesa": "🍔", "fruta": "🍎 🍌 🍇", "manzana": "🍎 🍏",
    "platano": "🍌", "plátano": "🍌", "fresa": "🍓", "pastel": "🎂 🍰",
    "cumpleanos": "🎂 🥳 🎉", "cumpleaños": "🎂 🥳 🎉", "chocolate": "🍫",
    "helado": "🍦 🍨", "cafe": "☕", "café": "☕", "leche": "🥛",
    "cerveza": "🍺 🍻", "vino": "🍷", "regalo": "🎁", "globo": "🎈",
    "trofeo": "🏆", "juego": "🎮 🕹️", "camara": "📷 📸", "cámara": "📷 📸",
    "telefono": "📱 📞", "teléfono": "📱 📞", "libro": "📖 📚", "lapiz": "✏️",
    "lápiz": "✏️", "idea": "💡", "llave": "🔑", "reloj": "⏰ 🕐",
    "dinero": "💰 💵", "diamante": "💎", "corona": "👑", "coche": "🚗 🚙",
    "autobus": "🚌", "autobús": "🚌", "tren": "🚆 🚄", "avion": "✈️",
    "avión": "✈️", "cohete": "🚀", "barco": "🚢 ⛵", "casa": "🏠 🏡",
    "escuela": "🏫", "futbol": "⚽", "fútbol": "⚽", "musica": "🎵 🎶",
    "música": "🎵 🎶", "guitarra": "🎸", "fiesta": "🥳 🎉 🎊", "si": "✅ 👍",
    "sí": "✅ 👍", "no": "❌ 🚫 👎",
}
FR = {
    "heureux": "😊 😄 😁 🥰", "rire": "😂 🤣 😆", "triste": "😢 😞 😔 🙁",
    "pleurer": "😭 😢", "colere": "😠 😡 🤬", "colère": "😠 😡 🤬",
    "amour": "😍 🥰 😘 ❤️ 💕", "coeur": "❤️ 🧡 💛 💚 💙 💜 🖤",
    "cœur": "❤️ 🧡 💛 💚 💙 💜 🖤", "bisou": "😘 💋", "feu": "🔥",
    "etoile": "⭐ 🌟 ✨", "étoile": "⭐ 🌟 ✨", "merci": "🙏",
    "main": "✋ 👋 🤚", "pouce": "👍 👎", "applaudir": "👏", "salut": "👋",
    "bonjour": "👋", "fort": "💪", "oeil": "👀 👁️", "cerveau": "🧠",
    "fantome": "👻", "fantôme": "👻", "robot": "🤖", "chien": "🐶 🐕",
    "chat": "🐱 🐈 😺", "lapin": "🐰 🐇", "ours": "🐻", "lion": "🦁",
    "cheval": "🐴 🐎", "oiseau": "🐦 🦅", "poisson": "🐟 🐠", "abeille": "🐝",
    "papillon": "🦋", "serpent": "🐍", "elephant": "🐘", "éléphant": "🐘",
    "fleur": "🌸 🌷 🌹 💐", "rose": "🌹", "arbre": "🌳 🌲", "soleil": "☀️ 🌞",
    "lune": "🌙 🌝", "pluie": "🌧️ ☔", "neige": "❄️ ⛄", "eau": "💧 💦 🌊",
    "mer": "🌊", "terre": "🌍 🌎 🌏", "montagne": "⛰️ 🏔️", "eclair": "⚡",
    "éclair": "⚡", "nourriture": "🍕 🍔 🍟", "pizza": "🍕", "burger": "🍔",
    "fruit": "🍎 🍌 🍇", "pomme": "🍎 🍏", "banane": "🍌", "fraise": "🍓",
    "gateau": "🎂 🍰", "gâteau": "🎂 🍰", "anniversaire": "🎂 🥳 🎉",
    "chocolat": "🍫", "glace": "🍦 🍨", "cafe": "☕", "café": "☕",
    "lait": "🥛", "biere": "🍺 🍻", "bière": "🍺 🍻", "vin": "🍷",
    "cadeau": "🎁", "ballon": "🎈", "trophee": "🏆", "trophée": "🏆",
    "jeu": "🎮 🕹️", "camera": "📷 📸", "caméra": "📷 📸",
    "telephone": "📱 📞", "téléphone": "📱 📞", "livre": "📖 📚",
    "crayon": "✏️", "idee": "💡", "idée": "💡", "cle": "🔑", "clé": "🔑",
    "horloge": "⏰ 🕐", "argent": "💰 💵", "diamant": "💎", "couronne": "👑",
    "voiture": "🚗 🚙", "bus": "🚌", "train": "🚆 🚄", "avion": "✈️",
    "fusee": "🚀", "fusée": "🚀", "bateau": "🚢 ⛵", "maison": "🏠 🏡",
    "ecole": "🏫", "école": "🏫", "football": "⚽", "musique": "🎵 🎶",
    "guitare": "🎸", "fete": "🥳 🎉 🎊", "fête": "🥳 🎉 🎊", "oui": "✅ 👍",
    "non": "❌ 🚫 👎",
}
IT = {
    "felice": "😊 😄 😁 🥰", "ridere": "😂 🤣 😆", "triste": "😢 😞 😔 🙁",
    "piangere": "😭 😢", "arrabbiato": "😠 😡 🤬", "amore": "😍 🥰 😘 ❤️ 💕",
    "cuore": "❤️ 🧡 💛 💚 💙 💜 🖤", "bacio": "😘 💋", "fuoco": "🔥",
    "stella": "⭐ 🌟 ✨", "grazie": "🙏", "mano": "✋ 👋 🤚", "pollice": "👍 👎",
    "applauso": "👏", "ciao": "👋", "forte": "💪", "occhio": "👀 👁️",
    "cervello": "🧠", "fantasma": "👻", "robot": "🤖", "cane": "🐶 🐕",
    "gatto": "🐱 🐈 😺", "coniglio": "🐰 🐇", "orso": "🐻", "leone": "🦁",
    "cavallo": "🐴 🐎", "uccello": "🐦 🦅", "pesce": "🐟 🐠", "ape": "🐝",
    "farfalla": "🦋", "serpente": "🐍", "elefante": "🐘",
    "fiore": "🌸 🌷 🌹 💐", "rosa": "🌹", "albero": "🌳 🌲", "sole": "☀️ 🌞",
    "luna": "🌙 🌝", "pioggia": "🌧️ ☔", "neve": "❄️ ⛄", "acqua": "💧 💦 🌊",
    "mare": "🌊", "terra": "🌍 🌎 🌏", "montagna": "⛰️ 🏔️", "fulmine": "⚡",
    "cibo": "🍕 🍔 🍟", "pizza": "🍕", "frutta": "🍎 🍌 🍇", "mela": "🍎 🍏",
    "banana": "🍌", "fragola": "🍓", "torta": "🎂 🍰",
    "compleanno": "🎂 🥳 🎉", "cioccolato": "🍫", "gelato": "🍦 🍨",
    "caffe": "☕", "caffè": "☕", "latte": "🥛", "birra": "🍺 🍻",
    "vino": "🍷", "regalo": "🎁", "palloncino": "🎈", "trofeo": "🏆",
    "gioco": "🎮 🕹️", "fotocamera": "📷 📸", "telefono": "📱 📞",
    "libro": "📖 📚", "matita": "✏️", "idea": "💡", "chiave": "🔑",
    "orologio": "⏰ 🕐", "soldi": "💰 💵", "diamante": "💎", "corona": "👑",
    "auto": "🚗 🚙", "treno": "🚆 🚄", "aereo": "✈️", "razzo": "🚀",
    "nave": "🚢 ⛵", "casa": "🏠 🏡", "scuola": "🏫", "calcio": "⚽",
    "musica": "🎵 🎶", "chitarra": "🎸", "festa": "🥳 🎉 🎊", "si": "✅ 👍",
    "sì": "✅ 👍", "no": "❌ 🚫 👎",
}
PT = {
    "feliz": "😊 😄 😁 🥰", "rir": "😂 🤣 😆", "triste": "😢 😞 😔 🙁",
    "chorar": "😭 😢", "raiva": "😠 😡 🤬", "amor": "😍 🥰 😘 ❤️ 💕",
    "coracao": "❤️ 🧡 💛 💚 💙 💜 🖤", "coração": "❤️ 🧡 💛 💚 💙 💜 🖤",
    "beijo": "😘 💋", "fogo": "🔥", "estrela": "⭐ 🌟 ✨", "obrigado": "🙏",
    "mao": "✋ 👋 🤚", "mão": "✋ 👋 🤚", "polegar": "👍 👎", "palmas": "👏",
    "ola": "👋", "olá": "👋", "forte": "💪", "olho": "👀 👁️",
    "cerebro": "🧠", "cérebro": "🧠", "fantasma": "👻", "robo": "🤖",
    "robô": "🤖", "cachorro": "🐶 🐕", "gato": "🐱 🐈 😺", "coelho": "🐰 🐇",
    "urso": "🐻", "leao": "🦁", "leão": "🦁", "cavalo": "🐴 🐎",
    "passaro": "🐦 🦅", "pássaro": "🐦 🦅", "peixe": "🐟 🐠", "abelha": "🐝",
    "borboleta": "🦋", "cobra": "🐍", "elefante": "🐘",
    "flor": "🌸 🌷 🌹 💐", "rosa": "🌹", "arvore": "🌳 🌲", "árvore": "🌳 🌲",
    "sol": "☀️ 🌞", "lua": "🌙 🌝", "chuva": "🌧️ ☔", "neve": "❄️ ⛄",
    "agua": "💧 💦 🌊", "água": "💧 💦 🌊", "mar": "🌊", "terra": "🌍 🌎 🌏",
    "montanha": "⛰️ 🏔️", "raio": "⚡", "comida": "🍕 🍔 🍟", "pizza": "🍕",
    "fruta": "🍎 🍌 🍇", "maca": "🍎 🍏", "maçã": "🍎 🍏", "banana": "🍌",
    "morango": "🍓", "bolo": "🎂 🍰", "aniversario": "🎂 🥳 🎉",
    "aniversário": "🎂 🥳 🎉", "chocolate": "🍫", "sorvete": "🍦 🍨",
    "cafe": "☕", "café": "☕", "leite": "🥛", "cerveja": "🍺 🍻",
    "vinho": "🍷", "presente": "🎁", "balao": "🎈", "balão": "🎈",
    "trofeu": "🏆", "troféu": "🏆", "jogo": "🎮 🕹️", "camera": "📷 📸",
    "câmera": "📷 📸", "telefone": "📱 📞", "livro": "📖 📚", "lapis": "✏️",
    "lápis": "✏️", "ideia": "💡", "chave": "🔑", "relogio": "⏰ 🕐",
    "relógio": "⏰ 🕐", "dinheiro": "💰 💵", "diamante": "💎", "coroa": "👑",
    "carro": "🚗 🚙", "onibus": "🚌", "ônibus": "🚌", "trem": "🚆 🚄",
    "aviao": "✈️", "avião": "✈️", "foguete": "🚀", "navio": "🚢 ⛵",
    "casa": "🏠 🏡", "escola": "🏫", "futebol": "⚽", "musica": "🎵 🎶",
    "música": "🎵 🎶", "violao": "🎸", "violão": "🎸", "festa": "🥳 🎉 🎊",
    "sim": "✅ 👍", "nao": "❌ 🚫 👎", "não": "❌ 🚫 👎",
}
RU = {
    "счастье": "😊 😄 😁 🥰", "смех": "😂 🤣 😆", "грусть": "😢 😞 😔 🙁",
    "плакать": "😭 😢", "злой": "😠 😡 🤬", "любовь": "😍 🥰 😘 ❤️ 💕",
    "сердце": "❤️ 🧡 💛 💚 💙 💜 🖤", "поцелуй": "😘 💋", "огонь": "🔥",
    "звезда": "⭐ 🌟 ✨", "спасибо": "🙏", "рука": "✋ 👋 🤚",
    "палец": "👍 👎", "хлопать": "👏", "привет": "👋", "пока": "👋",
    "сильный": "💪", "глаз": "👀 👁️", "мозг": "🧠", "призрак": "👻",
    "робот": "🤖", "собака": "🐶 🐕", "кошка": "🐱 🐈 😺", "кот": "🐱 🐈 😺",
    "заяц": "🐰 🐇", "медведь": "🐻", "лев": "🦁", "лошадь": "🐴 🐎",
    "птица": "🐦 🦅", "рыба": "🐟 🐠", "пчела": "🐝", "бабочка": "🦋",
    "змея": "🐍", "слон": "🐘", "цветок": "🌸 🌷 🌹 💐", "роза": "🌹",
    "дерево": "🌳 🌲", "солнце": "☀️ 🌞", "луна": "🌙 🌝", "дождь": "🌧️ ☔",
    "снег": "❄️ ⛄", "вода": "💧 💦 🌊", "море": "🌊", "земля": "🌍 🌎 🌏",
    "гора": "⛰️ 🏔️", "молния": "⚡", "еда": "🍕 🍔 🍟", "пицца": "🍕",
    "бургер": "🍔", "фрукт": "🍎 🍌 🍇", "яблоко": "🍎 🍏", "банан": "🍌",
    "клубника": "🍓", "торт": "🎂 🍰", "деньрождения": "🎂 🥳 🎉",
    "шоколад": "🍫", "мороженое": "🍦 🍨", "кофе": "☕", "чай": "🍵",
    "молоко": "🥛", "пиво": "🍺 🍻", "вино": "🍷", "подарок": "🎁",
    "шар": "🎈", "кубок": "🏆", "игра": "🎮 🕹️", "камера": "📷 📸",
    "телефон": "📱 📞", "книга": "📖 📚", "карандаш": "✏️", "идея": "💡",
    "ключ": "🔑", "часы": "⏰ 🕐", "деньги": "💰 💵", "алмаз": "💎",
    "корона": "👑", "машина": "🚗 🚙", "автобус": "🚌", "поезд": "🚆 🚄",
    "самолет": "✈️", "ракета": "🚀", "корабль": "🚢 ⛵", "дом": "🏠 🏡",
    "школа": "🏫", "футбол": "⚽", "музыка": "🎵 🎶", "гитара": "🎸",
    "вечеринка": "🥳 🎉 🎊", "да": "✅ 👍", "нет": "❌ 🚫 👎",
}

MODELS = {"en": EN, "tr": TR, "de": DE, "es": ES, "fr": FR, "it": IT,
          "pt": PT, "ru": RU}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for lang, model in MODELS.items():
        path = os.path.join(OUT_DIR, "search_" + lang + ".txt")
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            for kw in sorted(model):
                f.write(kw + "\t" + model[kw] + "\n")
        emoji_count = sum(len(v.split()) for v in model.values())
        print(f"wrote {path}  ({len(model)} keywords, {emoji_count} emoji refs)")


if __name__ == "__main__":
    main()
